services:
  backend:
    build: ./backend
    container_name: ai_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_BACKEND_URL=http://35.225.65.100:8000
    container_name: ai_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  mongodb:
    image: mongo:6
    container_name: ai_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
